project:
  type: website
  output-dir: docs

website:
  title: "Inferential Models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
      - href: tutorial.qmd
      - href: people.qmd
      
  announcement:
    icon: tools
    dismissable: true
    content: "This website is currently **under construction**."
    type: warning
    position: above-navbar
    
format:
  html:
    theme:
      # - cosmo
      # - brand
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

